// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itoaxstvcxfkifuzidyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0b2F4c3R2Y3hma2lmdXppZHlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODAzOTgsImV4cCI6MjA3MDU1NjM5OH0.rM8I4iVvLrVwXwKVi3u2phUDykP8BlvoOGckYWjdduM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});